apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arbeidsgiver-altinn-tilganger
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{ image }}}

  ingresses:
    - "https://arbeidsgiver-altinn-tilganger.intern.dev.nav.no"

  liveness:
    path: /internal/isalive

  readiness:
    path: /internal/isready

  prometheus:
    enabled: true
    path: /internal/prometheus

  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1024Mi

  env:
    - name: JAVA_OPTS
      value: "-XX:+UseParallelGC -XX:MaxRAMPercentage=75.0 -XX:ActiveProcessorCount=2"
    - name: ALTINN_3_API_BASE_URL
      value: https://platform.tt02.altinn.no
    - name: ALTINN_2_BASE_URL
      value: https://tt02.altinn.no

  envFrom:
    - secret: altinn-tilganger
  
  tokenx:
    enabled: true

  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "altinn:accessmanagement/authorizedparties.resourceowner"
        - name: "altinn:serviceowner/reportees"

  accessPolicy:
    inbound:
      rules:
        - application: tokenx-token-generator
          namespace: aura
          cluster: dev-gcp
    outbound:
      external:
        - host: platform.tt02.altinn.no
        - host: tt02.altinn.no

  redis:
    - instance: tilganger
      access: readwrite