name: Test, bygg, deploy
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # bygg nytt image hver mandag morgen


jobs:
  bygg-og-deploy:
    name: Bygg og deploy
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - run: mvn -B package

      - uses: nais/docker-build-push@v0
        id: gar-push
        with:
          team: fager
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: nais/deploy/actions/deploy@v2
        name: Deploy dev-gcp
        env:
          VAR: image=${{ steps.gar-push.outputs.image }}
          RESOURCE: nais/dev-gcp.yaml
          CLUSTER: dev-gcp


