name: Test, bygg, deploy
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # bygg nytt image hver mandag morgen


jobs:
  build:
    name: Bygg
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # mock-oauth2-server needs config from repo to start, so run it manually
      - run: >-
          /usr/bin/docker run -d
          -p 9000:9000
          -e "SERVER_PORT=9000"
          -e "JSON_CONFIG_PATH=./mock-oauth2-config.json"
          -v "./mock-oauth2-config.json":"/mock-oauth2-config.json"
          $(yq '.services.oauth.image' docker-compose.yaml)

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven

      - run: mvn -B package

      - uses: nais/docker-build-push@v0
        id: gar-push
        with:
          team: fager
          salsa: false
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    outputs:
      image: ${{ steps.gar-push.outputs.image }}
      digest: ${{ steps.gar-push.outputs.digest }}

  salsa:
    name: Generate SBOM, attest and sign image
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # https://github.com/navikt/dagpenger/blob/e1b4eef41fc5e7ad835d741972c718b85f343783/actions/attest-sign/action.yml
      - uses: navikt/dagpenger/actions/attest-sign@master
        with:
          team: fager
          digest: ${{ needs.build.outputs.digest }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy dev-gcp
        env:
          VAR: image=${{ needs.build.outputs.image }}
          RESOURCE: nais/dev-gcp.yaml
          CLUSTER: dev-gcp
