name: Test, bygg, deploy
on:
  push:
    paths:
      - nais/dev-gcp-redis.yaml
      - nais/prod-gcp-redis.yaml
  workflow_dispatch:

jobs:
  build:
    name: Bygg
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/dev-gcp-redis.yaml
          CLUSTER: dev-gcp

      - uses: nais/deploy/actions/deploy@v2
        if: github.ref == 'refs/heads/main'
        env:
          RESOURCE: nais/prod-gcp-redis.yaml
          CLUSTER: prod-gcp
